export const GET_LIST = 'GET_LIST';
export const SET_STRAINLIST = 'SET_STRAINLIST';
export const REQUEST_STRAINLIST = 'REQUEST_STRAINLIST';
export const SELECT_STRAIN = 'SELECT_STRAIN';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
